services:
  app_ts:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_TS_HASURA_SERVICE_TOKEN_SECRET
      OPENAI_API_KEY: $APP_TS_OPENAI_API_KEY
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_TS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_TS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 9789:8080
