services:
  bot-server:
    image: dev-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app/server
    env_file:
      - .env
    working_dir: /app/server
    command: ["bun", "--watch", "src/index.ts"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app/server