services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: pql-bot
      POSTGRES_USER: docs
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docs -d pql-bot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
